# Generated by Django 5.2 on 2025-04-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0003_scholarship_scholarshipapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='eligibility',
            field=models.CharField(choices=[('all', 'All'), ('basud', 'Basud'), ('capalonga', 'Capalonga'), ('daet', 'Daet'), ('jose panganiban', 'Jose Panganiban'), ('labo', 'Labo'), ('mercedes', 'Mercedes'), ('paracale', 'Paracale'), ('san lorenzo', 'San Lorenzo'), ('san vicente', 'San Vicente'), ('santa elena', 'Santa Elena'), ('talisay', 'Talisay'), ('vinzons', 'Vinzons')], default='all', max_length=30),
        ),
    ]
