# Generated by Django 5.2 on 2025-04-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0004_scholarship_eligibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='eligibility',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='eligibility',
            field=models.ManyToManyField(to='scholar.scholarship'),
        ),
    ]
