# Generated by Django 5.2 on 2025-04-14 16:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0006_remove_scholarship_eligibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='eligibility',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('all', 'All'), ('basud', 'Basud'), ('capalonga', 'Capalonga'), ('daet', 'Daet'), ('jose panganiban', 'Jose Panganiban'), ('labo', 'Labo'), ('mercedes', 'Mercedes'), ('paracale', 'Paracale'), ('san lorenzo', 'San Lorenzo'), ('san vicente', 'San Vicente'), ('santa elena', 'Santa Elena'), ('talisay', 'Talisay'), ('vinzons', 'Vinzons')], max_length=30), blank=True, default=list, size=None),
        ),
    ]
