# Generated by Django 5.2 on 2025-04-26 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0008_studentinformation_studentprofile_birth_date_and_more'),
    ]

    operations = [
        
    ]
