# Generated by Django 5.2 on 2025-04-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0009_remove_scholarshipapplication_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='fathers_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='fathers_birthdate',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='fathers_citizenship',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='fathers_contact_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='fathers_home_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='fathers_occupation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='fathers_religion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian',
            field=models.CharField(default='', max_length=130),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mothers_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mothers_birthdate',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mothers_citizenship',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mothers_contact_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mothers_home_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mothers_occupation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mothers_religion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='permanent_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='rel_in_guardian',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='fathers_first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='fathers_last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='mothers_first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='mothers_last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
