# Generated by Django 5.2 on 2025-04-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0010_studentprofile_fathers_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='fathers_birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='mothers_birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
