# Generated by Django 5.2 on 2025-04-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0011_alter_studentprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
