# Generated by Django 5.2 on 2025-04-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0012_alter_studentprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
