# Generated by Django 5.2 on 2025-04-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0013_customuser_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='fathers_age',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='fathers_birthdate',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='mothers_age',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='mothers_birthdate',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='fathers_middle_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mothers_middle_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
