# Generated by Django 5.2 on 2025-05-01 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0017_remove_studentprofile_guardian_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='permanent_address',
        ),
    ]
