# Generated by Django 5.2 on 2025-05-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0018_remove_studentprofile_permanent_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentInformation',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_already_filled_form',
            field=models.BooleanField(default=False),
        ),
    ]
