# Generated by Django 5.2 on 2025-05-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0019_delete_studentinformation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
