# Generated by Django 5.2 on 2025-05-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0020_alter_scholarship_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='grant_officer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='requirements',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
