# Generated by Django 5.2 on 2025-05-04 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0021_scholarship_grant_officer_scholarship_requirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='remarks',
        ),
    ]
