# Generated by Django 5.2 on 2025-05-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0022_remove_scholarshipapplication_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='municipality',
            field=models.CharField(choices=[('all', 'All'), ('basud', 'Basud'), ('capalonga', 'Capalonga'), ('daet', 'Daet'), ('jose panganiban', 'Jose Panganiban'), ('labo', 'Labo'), ('mercedes', 'Mercedes'), ('paracale', 'Paracale'), ('san lorenzo', 'San Lorenzo'), ('san vicente', 'San Vicente'), ('santa elena', 'Santa Elena'), ('talisay', 'Talisay'), ('vinzons', 'Vinzons')], default='', max_length=100),
        ),
    ]
