# Generated by Django 5.2 on 2025-05-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0023_studentprofile_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='remarks',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('reject', 'Reject')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='school_enrolled',
            field=models.CharField(choices=[('camarines norte state college', 'Camarines Norte State College'), ('our lady of lourdes college foundation', 'Our Lady of Lourdes College Foundation'), ('la consolacion college of daet, inc.', 'La Consolacion College of Daet, Inc.'), ('mabini colleges', 'Mabini Colleges'), ('camarines norte college', 'Camarines Norte College'), ('st. francis caracciolo culinary academy', 'St. Francis Caracciolo Culinary Academy '), ('camarines norte school of law', 'Camarines Norte School of Law')], default='', max_length=70),
        ),
    ]
