# Generated by Django 5.2 on 2025-05-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0024_scholarshipapplication_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Reject', 'Reject')], default='Pending', max_length=30),
        ),
    ]
