# Generated by Django 5.2 on 2025-05-21 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0025_alter_scholarshipapplication_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='scholar.scholarshipapplication')),
            ],
        ),
    ]
